version: "3.8"

services:
  web:
    image: razorit-web
    container_name: razorit-web
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
