version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: razorit-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAZORIT_API_URL=http://api.razorit.com
    restart: unless-stopped  # Ensures the container restarts if it crashes
