version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: razorit-web
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
