version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: razorit-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mount local files for hot reloading
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_RAZORIT_API_URL=${NEXT_PUBLIC_RAZORIT_API_URL}
      - NEXT_PUBLIC_RAZORIT_API_CLIENT_ID=${NEXT_PUBLIC_RAZORIT_API_CLIENT_ID}
      - NEXT_PUBLIC_RAZORIT_API_CLIENT_SECRET=${NEXT_PUBLIC_RAZORIT_API_CLIENT_SECRET}
    env_file:
      - .env
    command: ["sh", "-c", "yarn install && yarn dev"]
