version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: razorit-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app       # Mount local files for hot reloading
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000  # Connect frontend to backend
      - REACT_APP_CONTACT_EMAIL=info@razorit.com  # Email recipient for contact form
